# Generated by Django 5.0.4 on 2024-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
